/*!40101 SET NAMES utf8 */;
/*!40101 SET SQL_MODE=''*/;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


CREATE DATABASE IF NOT EXISTS `Portfolio` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `Portfolio`;


CREATE TABLE IF NOT EXISTS `portfolio_websites` (
 `Website_ID` INT NOT NULL AUTO_INCREMENT,
 `name` VARCHAR(60) NOT NULL,
 `url` VARCHAR(255) NOT NULL,
 `description` VARCHAR(2048) NOT NULL,
 `filter` VARCHAR(20) NOT NULL,
 `location` VARCHAR(255) NOT NULL,
 `location-alt` VARCHAR(255) NOT NULL,
 `monitor_preview` VARCHAR(255) NOT NULL,
 `tablet_preview` VARCHAR(255) NOT NULL,
 `phone_preview` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Website_ID`));



